test-pages:
  tags: [docker]
  image: alpine
  except:
    - master
  before_script:
    - apk update
    - apk add doxygen git texlive-full py3-jinja2 py3-pygments
    - git clone git://github.com/mosra/m.css
  script:
    - ./m.css/documentation/doxygen.py Doxyfile-mcss
    - mv generated-docs/html/ public/
  artifacts:
    paths:
      - public
  
pages:
  tags: [docker]
  image: alpine
  only:
    - master
  before_script:
    - apk update
    - apk add doxygen git texlive-full py3-jinja2 py3-pygments
    - git clone git://github.com/mosra/m.css
  script:
    - ./m.css/documentation/doxygen.py Doxyfile-mcss
    - mv generated-docs/html/ public/
  artifacts:
    paths:
      - public
